version: 2

project_name: driftwarden

before:
  hooks:
    - go mod tidy

builds:
  - id: driftwarden
    main: ./cmd/driftwarden
    binary: driftwarden
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.gitCommit={{.Commit}}
      - -X main.buildDate={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - docs/*

checksum:
  name_template: 'checksums.txt'

sboms:
  - id: default
    artifacts: archive
    documents:
      - "${artifact}.spdx.sbom"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
