package reconcile

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"

	"github.com/ShyamD2/driftwarden/pkg/models"
)

// GenerateHCLReconciliation synthesizes clean Terraform v1.5+ import blocks and resource definitions.
// Strictly enforces capabilities: resources with Reconcile == false produce warning comments, not invalid HCL.
func GenerateHCLReconciliation(report *models.ScanReport, outputPath string) ([]byte, error) {
	if report == nil {
		return nil, fmt.Errorf("scan report is nil")
	}

	var sb strings.Builder
	sb.WriteString("# ==============================================================================\n")
	sb.WriteString("# GENERATED CODE - NOT VERIFIED - REQUIRES HUMAN REVIEW\n")
	sb.WriteString("# Generated by DriftWarden (v1.0.0) GitOps HCL Synthesizer\n")
	sb.WriteString("# Review carefully before running 'terraform plan' or 'terraform apply'\n")
	sb.WriteString("# ==============================================================================\n\n")

	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()

	hasSupportedResources := false

	for _, item := range report.Items {
		res := item.Resource

		// 1. Capability Enforcement: Check if collector supports reconciliation
		if !item.Capabilities.Reconcile {
			commentBlock := fmt.Sprintf(
				"# ------------------------------------------------------------------------------\n"+
					"# Resource: %s (%s)\n"+
					"# Discovery: SUPPORTED | Reconciliation: UNSUPPORTED\n"+
					"# Action required: Manual import required for CloudControl-discovered resources.\n"+
					"# ------------------------------------------------------------------------------\n\n",
				res.Type, res.ProviderID,
			)
			sb.WriteString(commentBlock)
			continue
		}

		hasSupportedResources = true
		importID := resolveImportID(res)
		safeName := sanitizeResourceName(res)
		resourceAddress := fmt.Sprintf("%s.%s", res.Type, safeName)

		// 2. Synthesize modern Terraform 1.5+ import block
		importBlock := rootBody.AppendNewBlock("import", nil)
		importBody := importBlock.Body()
		importBody.SetAttributeRaw("to", hclwrite.TokensForIdentifier(resourceAddress))
		importBody.SetAttributeValue("id", cty.StringVal(importID))
		rootBody.AppendNewline()

		// 3. Synthesize skeleton declarative resource block
		resBlock := rootBody.AppendNewBlock("resource", []string{res.Type, safeName})
		resBody := resBlock.Body()

		// Populate basic attributes from live state
		for k, v := range res.Attributes {
			if strings.HasPrefix(k, "_") || k == "id" || k == "arn" {
				continue
			}
			switch val := v.(type) {
			case string:
				resBody.SetAttributeValue(k, cty.StringVal(val))
			case bool:
				resBody.SetAttributeValue(k, cty.BoolVal(val))
			case int:
				resBody.SetAttributeValue(k, cty.NumberIntVal(int64(val)))
			case int32:
				resBody.SetAttributeValue(k, cty.NumberIntVal(int64(val)))
			case int64:
				resBody.SetAttributeValue(k, cty.NumberIntVal(val))
			case float64:
				resBody.SetAttributeValue(k, cty.NumberFloatVal(val))
			}
		}

		if len(res.Tags) > 0 {
			tagMap := make(map[string]cty.Value)
			for tk, tv := range res.Tags {
				tagMap[tk] = cty.StringVal(tv)
			}
			resBody.SetAttributeValue("tags", cty.MapVal(tagMap))
		}

		rootBody.AppendNewline()
	}

	if hasSupportedResources {
		sb.Write(f.Bytes())
	}

	outBytes := []byte(sb.String())

	if outputPath != "" {
		if err := os.WriteFile(outputPath, outBytes, 0644); err != nil {
			return nil, fmt.Errorf("failed to write HCL file to %s: %w", outputPath, err)
		}
	}

	return outBytes, nil
}

// resolveImportID applies the exact per-resource import ID rules specified by Phase 6.
func resolveImportID(res models.CanonicalResource) string {
	switch res.Type {
	case "aws_instance":
		// ID = instance ID (i-xxxx)
		return res.ProviderID
	case "aws_ebs_volume":
		// ID = volume ID (vol-xxxx)
		return res.ProviderID
	case "aws_eip":
		// ID = allocation ID (eipalloc-xxxx)
		if allocID, ok := res.Attributes["allocation_id"].(string); ok && allocID != "" {
			return allocID
		}
		return res.ProviderID
	case "aws_security_group":
		// ID = SG ID (sg-xxxx)
		return res.ProviderID
	case "aws_s3_bucket":
		// ID = bucket name
		if bucketName, ok := res.Attributes["bucket"].(string); ok && bucketName != "" {
			return bucketName
		}
		return res.ProviderID
	case "aws_iam_role":
		// ID = role name
		if roleName, ok := res.Attributes["name"].(string); ok && roleName != "" {
			return roleName
		}
		return res.ProviderID
	case "aws_vpc", "aws_subnet", "aws_route_table":
		// ID = vpc/subnet/rtb ID
		return res.ProviderID
	default:
		return res.ProviderID
	}
}

var nonAlphanumeric = regexp.MustCompile(`[^a-zA-Z0-9_]`)

func sanitizeResourceName(res models.CanonicalResource) string {
	name := res.Name
	if name == "" {
		name = res.ProviderID
	}
	if name == "" {
		name = "reconciled_resource"
	}
	cleaned := nonAlphanumeric.ReplaceAllString(name, "_")
	cleaned = strings.Trim(cleaned, "_")
	if len(cleaned) == 0 {
		return "reconciled_resource"
	}
	// HCL identifier must start with letter or underscore
	if cleaned[0] >= '0' && cleaned[0] <= '9' {
		cleaned = "r_" + cleaned
	}
	return cleaned
}
