# ==============================================================================
# GENERATED CODE - NOT VERIFIED - REQUIRES HUMAN REVIEW
# Generated by DriftWarden (v1.0.0) GitOps HCL Synthesizer
# Review carefully before running 'terraform plan' or 'terraform apply'
# ==============================================================================

import {
  to = aws_security_group.web_prod_sg
  id = "sg-demo-web"
}

resource "aws_security_group" "web_prod_sg" {
  description = "Production web security group"
  name        = "web-prod-sg"
}

import {
  to = aws_s3_bucket.prod_assets
  id = "prod-assets-corp-bucket-12345"
}

resource "aws_s3_bucket" "prod_assets" {
  bucket                      = "prod-assets-corp-bucket-12345"
  public_access_block_enabled = false
}

import {
  to = aws_instance.unmanaged_shadow_host
  id = "i-rogue-shadow-99"
}

resource "aws_instance" "unmanaged_shadow_host" {
  instance_type = "t3.medium"
  tags = {
    CreatedBy = "unknown-console-user"
  }
}

