#!/usr/bin/env bash
# GENERATED BY DRIFTWARDEN - REQUIRES HUMAN REVIEW
# DriftWarden Safety Guard: Read-Only Boundary Enforced
# Generated: 2026-10-06T13:43:52Z
set -euo pipefail

EXECUTE=false
if [[ "${1:-}" == "--execute" ]]; then
  EXECUTE=true
fi

if [ "$EXECUTE" = false ]; then
  echo "[DRY-RUN] Running in dry-run mode. Pass --execute to apply changes."
fi

# Action 1: Revoke unrestricted SSH ingress (port 22) from 0.0.0.0/0 on sg-demo-web
# [CONFIDENCE: HIGH] [AUTOMATED_PR_ELIGIBLE]
CMD_1=("aws" "ec2" "revoke-security-group-ingress" "--group-id" "sg-demo-web" "--protocol" "tcp" "--port" "22" "--cidr" "0.0.0.0/0")
if [ "$EXECUTE" = true ]; then
  echo "[EXECUTE] Running: ${CMD_1[*]}"
  "${CMD_1[@]}"
else
  echo "[DRY-RUN] Would execute: ${CMD_1[*]}"
fi

# Action 2: Enable full Public Access Block on S3 bucket prod-assets-corp-bucket-12345
# [CONFIDENCE: HIGH] [AUTOMATED_PR_ELIGIBLE]
CMD_2=("aws" "s3api" "put-public-access-block" "--bucket" "prod-assets-corp-bucket-12345" "--public-access-block-configuration" "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true")
if [ "$EXECUTE" = true ]; then
  echo "[EXECUTE] Running: ${CMD_2[*]}"
  "${CMD_2[@]}"
else
  echo "[DRY-RUN] Would execute: ${CMD_2[*]}"
fi

# Action 3: Stop unmanaged shadow EC2 instance i-rogue-shadow-99 pending decommission
# [CONFIDENCE: MEDIUM] # REQUIRES_MANUAL_REVIEW
# Risk Warning: Shadow resource mutation has operational impact and requires manual verification before decommission.
CMD_3=("aws" "ec2" "stop-instances" "--instance-ids" "i-rogue-shadow-99")
if [ "$EXECUTE" = true ]; then
  echo "[EXECUTE] Running: ${CMD_3[*]}"
  "${CMD_3[@]}"
else
  echo "[DRY-RUN] Would execute: ${CMD_3[*]}"
fi

echo "[COMPLETE] Revert script execution finished."
