package normalizer

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ShyamD2/driftwarden/pkg/models"
)

// ComputedAttributesToStrip defines attributes generated by AWS runtime that are read-only
// and should not cause configuration drift.
var ComputedAttributesToStrip = map[string]bool{
	"arn":                  true,
	"owner_id":             true,
	"creation_date":        true,
	"availability_zone_id": true,
	"id":                   true,
}

// Normalizer handles semantic canonicalization, tag scrubbing, and metadata stripping.
type Normalizer struct {
	IncludeSystemDefaults bool
}

// NewNormalizer creates a new Normalizer instance.
func NewNormalizer(includeSystemDefaults bool) *Normalizer {
	return &Normalizer{
		IncludeSystemDefaults: includeSystemDefaults,
	}
}

// Normalize modifies a CanonicalResource in-place to apply all semantic normalization rules.
func (n *Normalizer) Normalize(res *models.CanonicalResource) {
	if res == nil {
		return
	}

	// 1. Tag Cleaning: Strip cloud-injected system tags
	n.cleanTags(res)

	// 2. Computed Metadata Stripping
	n.stripComputedAttributes(res)

	// 3. Security Group Canonicalization: Sort ingress/egress rules deterministically
	if res.Type == "aws_security_group" {
		n.canonicalizeSecurityGroup(res)
	}

	// 4. System Default Tagging
	n.tagSystemDefaults(res)
}

// CleanTags removes internal cloud provider tags (e.g. aws:*, aws:ec2launch:*, aws:cloudformation:*).
func (n *Normalizer) cleanTags(res *models.CanonicalResource) {
	if res.Tags == nil {
		return
	}
	cleaned := make(map[string]string)
	for k, v := range res.Tags {
		lowerK := strings.ToLower(k)
		if strings.HasPrefix(lowerK, "aws:") {
			continue
		}
		cleaned[k] = v
	}
	res.Tags = cleaned
}

// StripComputedAttributes removes read-only provider runtime metadata.
func (n *Normalizer) stripComputedAttributes(res *models.CanonicalResource) {
	if res.Attributes == nil {
		return
	}
	for k := range res.Attributes {
		if ComputedAttributesToStrip[strings.ToLower(k)] {
			delete(res.Attributes, k)
		}
	}
}

// CanonicalizeSecurityGroup sorts ingress/egress rules deterministically by Protocol:FromPort:ToPort:CIDR.
func (n *Normalizer) canonicalizeSecurityGroup(res *models.CanonicalResource) {
	for _, ruleKey := range []string{"ingress", "egress"} {
		if rawRules, ok := res.Attributes[ruleKey]; ok && rawRules != nil {
			if ruleList, ok := rawRules.([]any); ok {
				sortSGRules(ruleList)
				res.Attributes[ruleKey] = ruleList
			}
		}
	}
}

func sortSGRules(rules []any) {
	sort.SliceStable(rules, func(i, j int) bool {
		return ruleSortKey(rules[i]) < ruleSortKey(rules[j])
	})
}

func ruleSortKey(rule any) string {
	ruleMap, ok := rule.(map[string]any)
	if !ok {
		return fmt.Sprintf("%v", rule)
	}

	protocol := fmt.Sprintf("%v", ruleMap["protocol"])
	fromPort := fmt.Sprintf("%v", ruleMap["from_port"])
	toPort := fmt.Sprintf("%v", ruleMap["to_port"])
	cidr := ""
	if cidrBlocks, ok := ruleMap["cidr_blocks"].([]any); ok && len(cidrBlocks) > 0 {
		var strBlocks []string
		for _, b := range cidrBlocks {
			strBlocks = append(strBlocks, fmt.Sprintf("%v", b))
		}
		sort.Strings(strBlocks)
		cidr = strings.Join(strBlocks, ",")
	} else if c, ok := ruleMap["cidr_block"]; ok {
		cidr = fmt.Sprintf("%v", c)
	}

	return fmt.Sprintf("%s:%s:%s:%s", protocol, fromPort, toPort, cidr)
}

// TagSystemDefaults tags auto-generated default VPC security groups and route tables as IsDefault = true.
func (n *Normalizer) tagSystemDefaults(res *models.CanonicalResource) {
	switch res.Type {
	case "aws_security_group":
		if res.Name == "default" || res.Attributes["name"] == "default" {
			res.IsDefault = true
		}
	case "aws_route_table":
		if isMain, ok := res.Attributes["is_main"].(bool); ok && isMain {
			res.IsDefault = true
		}
	case "aws_vpc":
		if isDef, ok := res.Attributes["is_default"].(bool); ok && isDef {
			res.IsDefault = true
		}
	case "aws_subnet":
		if isDefAZ, ok := res.Attributes["default_for_az"].(bool); ok && isDefAZ {
			res.IsDefault = true
		}
	}
}

// ShouldSuppressSystemDefault checks if a resource should be filtered out from drift reporting
// because it is an auto-generated system default and --include-system-defaults is false.
func (n *Normalizer) ShouldSuppressSystemDefault(res models.CanonicalResource) bool {
	if n.IncludeSystemDefaults {
		return false
	}
	return res.IsDefault
}
